config/routes.rb
OurLook::Application.routes.draw do

  resources :users

  resources :items

  resources :sessions

  root :to => "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :name, :price, :url, :user_id, :count

  has_many :reviews
  has_and_belongs_to_many :users

  def is_available?
  	self.count > 0 
  end 

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :item_id, :text, :user_id

  belongs_to :user
  belongs_to :item 
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

  attr_accessible :email, :name, :password, :password_confirmation

	has_and_belongs_to_many :items
	has_many :reviews  

  validates :email, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	if session[:email]
  		@current_user = User.find_by_email(session[:email])
  	end
  end

  helper_method :current_user

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @dress = Item.find(1)
    @purse = Item.find(2)
    @shorts = Item.find(3)
    @heels = Item.find(4)
    @ring = Item.find(5)
  end

  def show
    @item = Item.find(params[:id])
  end

  def destroy
  end

  def edit
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.is_available?
        @item.update_attributes(:count => @item.count -= 1)
        @item.users << current_user
        format.js { render :action => "purchased"}
      else
        format.js { render :action => "out_of_stock"}
      end
    end 
  end

  def update
    @item = Item.find(params[:id])
    @review = Review.create(:text => params[:review], :item_id => @item.id, :user_id => current_user.id)
    
    respond_to do |format|
      format.js { render :action => "review"}
    end
  end

  def create
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
  	@user = User.find_by_email(params[:email])
  	if @user.authenticate(params[:password])
  		session[:email] = @user.email
  		redirect_to user_path(@user.id), :notice => "You're logged in:)"
		end
  end

  def destroy
  	session[:email] = nil
    redirect_to root_path, :notice => "You're logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:email] = @user.email
      redirect_to @user
    else
      render action: "new"
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.haml
%h1#our_look OurLook


%div#images_main
	
	=link_to item_path(@heels.id) do
		%img#heels_main{:src => "#{@heels.url}"}

	=link_to item_path(@dress.id) do
		%img#dress_main{:src => "#{@dress.url}"}

	=link_to item_path(@ring.id) do
		%img#ring_main{:src => "#{@ring.url}"}

	=link_to item_path(@purse.id) do
		%img#purse_main{:src => "#{@purse.url}"}

	=link_to item_path(@shorts.id) do
		%img#shorts_main{:src => "#{@shorts.url}"}

%p#click (Click a piece.) 

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/out_of_stock.js.erb
$(document ).ready(function() {

$(".description").text("So sorry, this item is out of stock. Try again soon!")

});

app/views/items/purchased.js.erb
$(document ).ready(function() {

$(".description").text("Purchased! All yours :)")

});

app/views/items/review.js.erb
$(document ).ready(function() {

$("#reviews").append("<%= @review.text %> -- <%= @review.user.name %> </br>")

});

app/views/items/show.haml
%p#notice= notice

%h2#item_name= @item.name

%img{:src => "#{@item.url}"}

%div.description
	=@item.description 
	=@item.price
	=link_to "Buy this!", edit_item_path(@item.id), :remote => true


	%h3 Reviews:

	%ul#reviews
		-@item.reviews.each do |review|
			%li #{review.text} --#{review.user.name}

	%h4 Write a review for this item: 

	= form_tag("/items/#{@item.id}", method: "put", :remote => true) do
		= label_tag "What'd you think?!"
		= text_field_tag (:review)
		= submit_tag ("Submit Review")

%br
%br
=link_to "Back to OurLook", items_path

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OurLook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
<% if current_user %>
	Logged in as: <%=link_to current_user.email, user_path(current_user.id) %> |
	<%= link_to "Log out", "/sessions/#{current_user.id}", :method => "delete" %>
<% else %>
	<%= link_to "Sign Up", new_user_path %> |
	<%= link_to "Log in", new_session_path %> 
<% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up for OurLook!</h1>

<%= form_for(@user) do |f| %>

	<div class="field">
	  <%= f.label "Name (first and last):" %> <br/>
	  <%= f.text_field :name %>
	</div>

	<div class="field">
	  <%= f.label "Email (this will be your username):" %> <br/>
	  <%= f.text_field :email %>
	</div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up!" %>
  </div>
  
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class = "orange"> Hi, <%=current_user.name%>! </h3>

<h4 class = "orange"> Purchased Items: </h4>

<ul>
	<% current_user.items.uniq.each do |item| %>
	<li>
		<img src = "<%= item.url %>" >
		<%= item.name %>
		</br>
		<%= item.price %>
		Quantity: <%= item.users(current_user).length %>
		<%= link_to "Tell the OurLook community what you thought!", item_path(item.id) %>
	</li>	
	</br>
	<% end %>
</ul>

<%= link_to "Back to OurLook", items_path %>